Upload manager refactor
cloverstudio/SpikaAndroid pull request #274
Opened 2023-07-26 12:22 UTC by ivolarevic

# Description

Refactored:
- uploading file logic (with canceling and re-sending)
- - refactored sending in ChatMessagesFragment
- - added UploadService and FileHelper class
- @MatkoTom implemented new scroll state logic + some scroll fixes for new logic
- added fixed dimensions for images and videos 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

# How Has This Been Tested?

Dev testing.

**Test Configuration**:

* Firmware version: G930FXXS7ETA1
* Hardware: Samsung galaxy s7
* SDK: Android 8, Oreo

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-07-27 10:48 UTC, MatkoTom commented on app/src/main/AndroidManifest.xml
> +    <uses-feature
What is telephony used for here? To save contact numbers to the phone or?

2023-07-27 10:49 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/BaseViewModel.kt
> +            else -> Timber.d("TODO")
Write a coherent message here so we know where to look for the issue. Just write a message that something failed in this viewmodel

2023-07-27 10:56 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/MediaFragment.kt
> +            requireActivity().onBackPressed()
Check if this onBackPressed() is deprecated and implement the new handling, if so

2023-07-27 10:57 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/settings/SettingsFragment.kt
> +                            // Ignore
I guess user cannot stop avatar uploads? Just confirm if so

2023-07-27 10:58 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/onboarding/account_creation/AccountCreationFragment.kt
> +
Same as comment before, also add // Ignore if not used.

2023-07-27 11:04 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/helpers/UploadService.kt
> +            null
What is this null value here?

2023-07-27 11:05 UTC, MatkoTom commented on app/src/main/res/layout/file_layout.xml
> +        android:layout_width="28dp"
Also, usee extracted values here

2023-07-27 11:06 UTC, MatkoTom commented on app/src/main/res/layout/item_message_me.xml
> +                        android:layout_width="30dp"
Extracted values are needed here too

2023-07-27 11:07 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatAdapter.kt
> +                                .diskCacheStrategy(DiskCacheStrategy.ALL)
I think this is the default value when using glide, check it

2023-07-27 11:09 UTC, MatkoTom requested changes
Check comments, still need to look at the permission though.

2023-07-27 12:47 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/BaseViewModel.kt
> +            else -> Timber.d("TODO")
Done.

2023-07-27 13:04 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/MediaFragment.kt
> +            requireActivity().onBackPressed()
Done, updated all.

2023-07-27 13:05 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/settings/SettingsFragment.kt
> +                            // Ignore
For now no because we need to remove all uploading logic to UploadService and then it would be possible to stop avatar upload.

2023-07-28 05:13 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/utils/helpers/UploadService.kt
> +            null
That is replyId. I refactored code like this: 
val jsonMessage = JsonMessage(
            msgText = text,
            mimeType = messageFileType,
            fileId = fileId,
            thumbId = thumbId,
            roomId = roomId,
            localId = localId,
            replyId = null
        )

2023-07-28 05:16 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatAdapter.kt
> +                                .diskCacheStrategy(DiskCacheStrategy.ALL)
Default is DiskCacheStrategy.AUTOMATIC

2023-07-28 06:02 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/onboarding/number_registration/RegisterNumberFragment.kt
Got some questions here:

1. Do we need to always ask for all of these permissions? Some of the require certain versions of Android or don't exist before certain versions.

2. What happens if you ask for notification permission on devices targetting < TIRAMISU? WIll it deefault to GRANTED, or will this fail?

Maybe we should take care of these permissions by checking user's Android version and then ask for the permissions that concern him?

2023-07-28 06:03 UTC, MatkoTom requested changes
Check comment about permissions. Make adjustments if necessary.

2023-07-31 11:32 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/AppPermissions.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
Don't think you need versions from TIRAMISU and later for the READ_CONTACTS permissions

2023-07-31 11:33 UTC, MatkoTom requested changes
Small mistake when asking for permissions. I know it is not used anywhere, but the issue needs to be resolved :)

2023-07-31 18:34 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/utils/AppPermissions.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
Done

2023-08-01 05:56 UTC, MatkoTom approved these changes
LGTM

2023-08-01 06:06 UTC, merged