Service Refactor, Upload Avatars
cloverstudio/SpikaAndroid pull request #396
Opened 2024-01-22 12:31 UTC by MatkoTom

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.

Branch contains work for uploading avatars via our service class. Also updated the service class to be more flexible and to make future event handling easier.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration. All testing was done
manually by following, plainly, functionality requirements. If there are some special edge cases or
special ways that things need to be tested they will be mentioned below.

Dev testing

**Test Configuration**:

* Firmware version:
* Hardware: SAMSUNG Galaxy S22
* SDK: Android 14

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2024-01-22 13:19 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat_details/ChatDetailsFragment.kt
> +                currentPhotoLocation,
can you maybe add: fileUri = currentPhotoLocation, etc.?

2024-01-22 13:20 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat_details/ChatDetailsFragment.kt
> +                    fileUploadService.uploadAvatar(avatarData!!, isGroup = true)
can we remove this "!!" ?

2024-01-22 13:22 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/settings/SettingsFragment.kt
> +                Const.JsonFields.AVATAR_TYPE,
same thing here

2024-01-22 13:23 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/settings/SettingsFragment.kt
> +            fileUploadService.uploadAvatar(avatarData!!, isGroup = false)
can we remove this "!!"?

2024-01-22 13:24 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/utils/helpers/UploadService.kt
> +                }
why?

2024-01-22 13:29 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatMessagesFragment.kt
> +            }
Also, if we dont use this method in ChatMessagesFragment can we remove it?

2024-01-22 13:30 UTC, ivolarevic requested changes
Please check comments and commit fixes.

2024-01-23 07:03 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/helpers/UploadService.kt
> +                }
It is currently using an indeterminate spinner instead of a progress one. And there is no cancel option implemented there.

2024-01-23 07:04 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatMessagesFragment.kt
> +            }
Removed

2024-01-23 07:18 UTC, ivolarevic approved these changes
LGTM

2024-01-23 11:22 UTC, ivolarevic approved these changes
LGTM

2024-01-23 12:30 UTC, merged