Giphy gifs
cloverstudio/SpikaAndroid pull request #428
Opened 2024-02-29 10:07 UTC by ivolarevic

# Description

Implemented Giphy gifs in the app.

<img src="https://github.com/cloverstudio/SpikaAndroid/assets/46626092/879520a4-c1f0-49ce-8bc1-c8e0a20c2321" width="50%" height="50%">

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Dev testing.

**Test Configuration**:

* Firmware version: G930FXXS7ETA1
* Hardware: Samsung galaxy s7
* SDK: Android 8, Oreo

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2024-02-29 12:10 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatMessagesFragment.kt
> +                val connection: HttpURLConnection = url.openConnection() as HttpURLConnection
This connection variable should be called withContext(). The Coroutine might get blocked and lead to thread starvation. It should be destroyed with the activity/fragment it lives in.

2024-02-29 12:13 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatMessagesFragment.kt
>                              localId = unsentMessage.localId!!,
We might try to resolve this !! now

2024-02-29 12:13 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatMessagesFragment.kt
> +            roomId = roomWithUsers!!.room.roomId,
Try and resolve this !! here

2024-02-29 12:13 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/ui/main/chat/ChatMessagesFragment.kt
> +                roomId = roomWithUsers!!.room.roomId,
Here too, the !!

2024-02-29 12:18 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/Tools.kt
> +            mimeType.contains(Const.JsonFields.SVG_TYPE) -> Const.JsonFields.FILE_TYPE
Should GIF types also be handled here?

2024-02-29 12:19 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/Tools.kt
> +        Timber.d("TYPE::::::::: $type")
You can remove this log

2024-02-29 12:19 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/UploadDownloadManager.kt
> +        Timber.d("MIME TYPE:::: $mimeType")
This log can also be removed

2024-02-29 12:20 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/UploadDownloadManager.kt
> +                        fileType = file.type!!,
Try and remove !! here

2024-02-29 12:20 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/UploadDownloadManager.kt
> +                        fileType = file.type!!,
Here too !!

2024-02-29 12:21 UTC, MatkoTom commented on app/src/main/java/com/clover/studio/spikamessenger/utils/helpers/FilesHelper.kt
> +                inputStream = inputStream!!,
!! here too

2024-02-29 12:21 UTC, MatkoTom requested changes
Check the comments and make the required adjustments.

2024-02-29 12:51 UTC, ivolarevic commented on app/src/main/java/com/clover/studio/spikamessenger/utils/Tools.kt
> +            mimeType.contains(Const.JsonFields.SVG_TYPE) -> Const.JsonFields.FILE_TYPE
No.

2024-03-05 07:10 UTC, MatkoTom approved these changes
LGTM

2024-03-05 07:27 UTC, merged